language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t jlei/react-docker -f Dockerfile.dev .

script:
    - docker run -e CI=true jlei/react-docker npm run test